# 配置文件
server:
    port: 9527

database:
    driver: postgres
    user: postgres
    passwd: langong@2023
    addr: 127.0.0.1
    port: 5432
    dbName: test
    zone: Asia/Shanghai

jwt:
    key: sunny1920

mqtt:
    server: tcp://127.0.0.1:1883
    clientID: test
    username: admin
    password: public
    topic: test/+

log:
    path: logger
    sunny: true
    sql: true